language: rust
dist: trusty

env:

matrix:
  include:
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
    - os: linux
      rust: stable
      env: TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
  allow_failures:
    - os: linux
      rust: stable
      env: TARGET=aarch64-unknown-linux-gnu
    - os: linux
      rust: stable
      env: TARGET=i686-unknown-linux-gnu

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=$TRAVIS_RUST_VERSION
  - export PATH="$PATH:$HOME/.cargo/bin"
  - rustc -V
  - cargo -V
  - if [[ "${TARGET}" == "i686-unknown-linux-gnu" ]]; then rustup target add $TARGET; fi
  - |
    if [[ "${TARGET}" == "aarch64-unknown-linux-gnu" ]]; then
        rustup target add $TARGET
        aarch64-linux-gnu-gcc -v
        mkdir -p .cargo
        echo "[target.${TARGET}]" > .cargo/config
        echo "linker = \"aarch64-linux-gnu-gcc\"" >> .cargo/config
        cat .cargo/config
    fi
  - git --version
  - echo $TRAVIS_BRANCH
  - git checkout $TRAVIS_BRANCH
  - git rev-parse HEAD

script:
  - cargo build --target $TARGET
  #- RUST_TEST_TASKS=1 cargo test --verbose

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - gcc-4.8-multilib
      - gcc-4.8-aarch64-linux-gnu
      - gcc-aarch64-linux-gnu
      - libc6-arm64-cross
      - libc6-dev-arm64-cross

before_deploy:
  - cargo build --target $TARGET --release
  - mkdir "kamasu-${TRAVIS_TAG}-${TARGET}"
  - cp target/$TARGET/release/kamasu LICENSE.txt README.md "kamasu-${TRAVIS_TAG}-${TARGET}"
  - zip "kamasu-${TRAVIS_TAG}-${TARGET}.zip" -r "kamasu-${TRAVIS_TAG}-${TARGET}"

deploy:
  provider: releases
  api_key:
    secure: bIPGui5pQ2kbpTBUhznaAqNqa26xMYwUi2/bc30tMBwDUz0htAP6vrEnX80TM5OrwVuD42pz8w8nzC7J+8btzSECjBzK2l7e4QSIki9875doLpOHjJDi1vdOs4htaXmVOal0E3Gkwjrxtzk+HOGJOFVXtnU2gMM4YnSlOrQAlGFP3Fb4zP0pImLLBvWu/jyXoD/rr5Z6/5Y4CyegjBHJozJGwkoJGx6NOdHIPruw95NH6eqzMMgvZE0NQndyN7AkdVNI4thXfTSOwA6oAh6LtMX9JIvfj9xMSvttzZOReVM46TDexKs6mVfbvemqfhLlw+MKqjHeyDL5gW8tcd6ODjtDtCrv7kJ4rJ0omn+2r8Wv0hP+6iJUSIXxbgstxbYIKFGUT/nJ5A8mM3Iz6xBvOvxXza6iM9F8SyMIIhbsyEP3ngZcI69PGLrNES0qDldIDt6R9BJJp41XPmODL0bHbHN5BXNzX58eqf3qQaft317mCNjIh0dI8pM1/3/XtYbgiagKJ2Xued9ZS/ZX9HJMUZlOLiyIucKWPcpEHBLMpqJMp9f3Fk98oFpxm/NKNNrZkrEELDtVZu4zf2osJnj4ZKGPg8lc+zabAGVHT+FhdPjsb4rdE4IhG037ksFJOli1xd72kPX0kNpGQz5p2gkhvJthUecCXAfxhjnU3KPq7kM=
  file: kamasu-${TRAVIS_TAG}-${TARGET}.zip
  skip_cleanup: true
  on:
    repo: hhatto/kamasu
    # On specific condition -> condition: $TRAVIS_RUST_VERSION = nightly
    #
    # Only deploy tagged commit
    tags: true
